---
- name: Build and deploy a Docker container
  hosts: localhost
  connection: local
  tasks:
    - name: Stop current running container
      docker_container:
        name: web-container
        state: stopped
      ignore_errors: yes

    - name: Remove stopped container
      docker_container:
        name: web-container
        state: absent
      ignore_errors: yes

    - name: Remove comingsoon-image
      docker_image:
        name: triple3a/comingsoon-page
        state: absent
      ignore_errors: yes

    - name: Build docker image using the Dockerfile
      docker_image:
        name: triple3a/comingsoon-page
        path: .
        tag: latest

    - name: Push image to Docker Hub
      docker_image_push:
        name: triple3a/comingsoon-page

    - name: Run container
      docker_container:
        name: web-container
        image: triple3a/comingsoon-page:latest
        state: started
        ports:
          - "5000:80"
